source 'https://rubygems.org'
gem "minima"
gem "plainwhite"
gem "jekyll-seo-tag"
gem "jekyll-feed"
gem "jekyll-remote-theme"
gem "webrick"

group :jekyll_plugins_github do
  gem "jekyll-coffeescript"
  gem "jekyll-default-layout"
  gem "jekyll-gist"
  gem "jekyll-github-metadata"
  gem "jekyll-optional-front-matter"
  gem "jekyll-paginate"
  gem "jekyll-readme-index"
  gem "jekyll-titles-from-headings"
  gem "jekyll-relative-links"
end
